version: '3.7'

services:
  metric-exchange:
    image: nikitahohulia/metric-converter-metric-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - metric-convert-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  metric-conversion:
    image: nikitahohulia/metric-converter-metric-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    networks:
      - metric-convert-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: nikitahohulia/metric-converter-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - metric-convert-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans


  naming-server:
    image: nikitahohulia/metric-converter-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - metric-convert-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    networks:
      - metric-convert-network


networks:
  metric-convert-network: